language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    # Laravel 5.5
    - php: 7.1
      env: LARAVEL=5.5.* TESTBENCH=3.5.*
    - php: 7.2
      env: LARAVEL=5.5.* TESTBENCH=3.5.*

    # Laravel 5.6
    - php: 7.1
      env: LARAVEL=5.6.* TESTBENCH=3.6.*
    - php: 7.2
      env: LARAVEL=5.6.* TESTBENCH=3.6.*

    # Laravel 6
    - php: 7.2
      env: LARAVEL=6.* TESTBENCH=4.*
    - php: 7.3
      env: LARAVEL=6.* TESTBENCH=4.*
    - php: 7.4
      env: LARAVEL=6.* TESTBENCH=4.*

    # Laravel 7
    - php: 7.2
      env: LARAVEL=7.* TESTBENCH=5.*
    - php: 7.3
      env: LARAVEL=7.* TESTBENCH=5.*
    - php: 7.4
      env: LARAVEL=7.* TESTBENCH=5.*

before_install:
  - composer self-update --stable --no-interaction
  - composer require orchestra/testbench:$TESTBENCH --no-update --no-interaction --dev

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist
