version: '3.8'

services:
    php-7.1:
        build: .
        volumes:
            - .:/opt/package
        environment:
            TESTBENCH: '5.0'

    php-7.1_laravel-5.5:
        build:
            dockerfile: Dockerfile-php7.1
        environment:
            TESTBENCH: '3.5'

    php-7.1_laravel-5.6:
        build:
            dockerfile: Dockerfile-php7.1
        environment:
            TESTBENCH: '3.6'

    php-7.1_laravel-5.7:
        build:
            dockerfile: Dockerfile-php7.1
        environment:
            TESTBENCH: '3.7'

    php-7.1_laravel-5.8:
        build:
            dockerfile: Dockerfile-php7.1
        environment:
            TESTBENCH: '3.8'

    php-7.2_laravel-6:
        build:
            dockerfile: Dockerfile-php7.2
        environment:
            TESTBENCH: '4.0'

    php-7.2_laravel-7:
        build:
            dockerfile: Dockerfile-php7.2
        environment:
            TESTBENCH: '5.0'

    php-7.3_laravel-7:
        build:
            dockerfile: Dockerfile-php7.3
        environment:
            TESTBENCH: '5.0'

    php-7.4_laravel-7:
        build:
            dockerfile: Dockerfile-php7.4
        environment:
            TESTBENCH: '5.0'

    php-8.0_laravel-8:
        build:
            dockerfile: Dockerfile-php8.0
        environment:
            TESTBENCH: '6.0'

    php-8.1_laravel-8:
        build:
            dockerfile: Dockerfile-php8.1
        environment:
            TESTBENCH: '6.0'
